name: "Choose an Issue Template"
about: Select a template for your issue.
labels:
  - "enhancement"
  - "bug"
  - "task"

# Optional: Preview a description on the "Choose an Issue Template" page.
templates:
  - name: "Feature Request"
    description: "Request a new feature or enhancement."
    file: "feature-request.md"
  - name: "Bug Report"
    description: "Report a bug or unexpected behavior."
    file: "bug-report.md"
  - name: "Task"
    description: "Create a task for development or other work."
    file: "task-template.md"
